### ISSUE TITLE
Ошибка с рисунками

### ISSUE THREAD

**Issue by KorobetskayaAA** [IrinaTimasheva/Plitka#1]
Почти все верно, но у меня на компьютере рисунки не отображаются (и на любом другом не будут). 
![изображение](https://user-images.githubusercontent.com/22618142/80496071-bf321500-8979-11ea-90f1-1346424c2784.png)

Потому что пути к файлам нужно писать относительные, а не полные. Например, вместо
``` xaml
Source="G:\Разработка мобильных приложений\СМОТРЕТЬ\Plitka\Plitka\res/svesda.png"
```
надо
``` xaml
Source="res/svesda.png"
```

А самим файлам рисунков надо в настройках указать тип "Ресурс", и чтобы они к exe-файлу автоматически копировались
![изображение](https://user-images.githubusercontent.com/22618142/80496165-dd981080-8979-11ea-851c-32c96cc1aa09.png)

**Comment by IrinaTimasheva** [comment]
Исправила!
